/*
This work was supported by the United States Member State Support Program to IAEA Safeguards;
the U.S. Department of Energy, Office of Nonproliferation and National Security, International
Safeguards Division; and the U.S. Department of Energy, Office of Safeguards and Security.

LA-CC-14-089. This software was exported from the United States in accordance with the Export
Administration Regulations. Diversion contrary to U.S. law prohibited.

Copyright 2015, Los Alamos National Security, LLC. This software application and associated
material ("The Software") was prepared by the Los Alamos National Security, LLC. (LANS), under
Contract DE-AC52-06NA25396 with the U.S. Department of Energy (DOE). All rights in the software
application and associated material are reserved by DOE on behalf of the Government and LANS
pursuant to the contract.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of
conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of
conditions and the following disclaimer in the documentation and/or other materials provided
with the distribution.
3. Neither the name of the "Los Alamos National Security, LLC." nor the names of its contributors
may be used to endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS
NATIONAL SECURITY, LLC OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRAT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
*/
// ICB.idl : IDL source for ICB Interface definition
//

// This file will be processed by the MIDL tool

import "oaidl.idl";
	[
		object,
		uuid(CE6E7E5C-77FA-433F-AE7E-8684CBA460F2),
	]
	interface ICB : IDispatch
	{
		[id(1), helpstring("method get_FaceColor")] HRESULT get_FaceColor([out] ULONG *pRGBvalue);
		[id(2), helpstring("method get_Numeric")] HRESULT get_Numeric([out] ULONG *pNumeric);

		[id(3), helpstring("method put_DisplayNumericString")] HRESULT put_DisplayNumericString([in] VARIANT_BOOL vb, [in] ULONG uRadix);
		[id(4), helpstring("method put_FaceColor")] HRESULT put_FaceColor([in] ULONG RGBcolor);
		[id(5), helpstring("method put_Flash")] HRESULT put_Flash([in] VARIANT_BOOL vb);
		[id(6), helpstring("method put_Numeric")] HRESULT put_Numeric([in] ULONG newValue);
		[id(7), helpstring("method put_PreNumericString")] HRESULT put_PreNumericString([in] BSTR string);


		[id(8), helpstring("method SetDiskIcon_Floppy")] HRESULT SetDiskIcon_Floppy();
		[id(9), helpstring("method SetDiskIcon_Hourglass")] HRESULT SetDiskIcon_Hourglass();

		[id(10), helpstring("method SetErrorIcon_Bomb")] HRESULT SetErrorIcon_Bomb();
		[id(11), helpstring("method SetErrorIcon_Flag")] HRESULT SetErrorIcon_Flag();
		[id(12), helpstring("method SetErrorIcon_Skull")] HRESULT SetErrorIcon_Skull();

		[id(13), helpstring("method SetMICObjectHandle")] HRESULT SetMICObjectHandle([in] ULONG handle);

		//was SetBell(bool)
		[id(14), helpstring("method ShowIcon_Bell")] HRESULT ShowIcon_Bell([in] VARIANT_BOOL vb);

		//was SetTime(bool)
		[id(15), helpstring("method ShowIcon_Clock")] HRESULT ShowIcon_Clock([in] VARIANT_BOOL vb);

		//was SetDisk(bool)
		[id(16), helpstring("method ShowIcon_Disk")] HRESULT ShowIcon_Disk([in] VARIANT_BOOL vb);

		//was SetFlag(bool)
		[id(17), helpstring("method ShowIcon_Error")] HRESULT ShowIcon_Error([in] VARIANT_BOOL vb);

		//was SetOthr(bool)
		[id(18), helpstring("method ShowIcon_Frown")] HRESULT ShowIcon_Frown([in] VARIANT_BOOL vb);

		//was SetQuest(bool)
		[id(19), helpstring("method ShowIcon_Square")] HRESULT ShowIcon_Square([in] VARIANT_BOOL vb);

		[id(20), helpstring("method get_VersionString")] HRESULT get_VersionString([out] BSTR *pbstrVersionString);

	};