/*
This work was supported by the United States Member State Support Program to IAEA Safeguards;
the U.S. Department of Energy, Office of Nonproliferation and National Security, International
Safeguards Division; and the U.S. Department of Energy, Office of Safeguards and Security.

LA-CC-14-089. This software was exported from the United States in accordance with the Export
Administration Regulations. Diversion contrary to U.S. law prohibited.

Copyright 2015, Los Alamos National Security, LLC. This software application and associated
material ("The Software") was prepared by the Los Alamos National Security, LLC. (LANS), under
Contract DE-AC52-06NA25396 with the U.S. Department of Energy (DOE). All rights in the software
application and associated material are reserved by DOE on behalf of the Government and LANS
pursuant to the contract.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of
conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of
conditions and the following disclaimer in the documentation and/or other materials provided
with the distribution.
3. Neither the name of the "Los Alamos National Security, LLC." nor the names of its contributors
may be used to endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS
NATIONAL SECURITY, LLC OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRAT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
*/
// ICSO.idl : IDL source for the ICSO interface
//

// This file will be processed by the MIDL tool


import "oaidl.idl";
	[
		object,
		uuid(B7180771-895F-417E-8239-353EE09F7009),
	]
	interface ICSO : IDispatch
	{
		typedef [v1_enum]  //32 bit alignment
		enum tagISO_FUNCTIONAL_CATEGORY
		{
			STANDARD_ISO     = 0,
			WATCH_ISO        = 1,
			UPS_ISO          = 2,
			UNKNOWN_ISO      = 99
		} ISO_FUNCTIONAL_CATEGORY;

		[id(1), helpstring("method CollectParametersForNewCSO")] 
			HRESULT CollectParametersForNewCSO(
				[out] BSTR *pbstrNameOut,
				[out] VARIANT_BOOL *pvbHaveNewCSO);

		[id(2), helpstring("method EnableHeartbeat")] HRESULT EnableHeartbeat([in] VARIANT_BOOL vbCommand);
		[id(3), helpstring("method get_CSOTypeString")] HRESULT get_CSOTypeString([out] BSTR *pbstrTypeString);
		[id(4), helpstring("method get_LastError")] HRESULT get_LastError([out] BSTR *pbstrErrorString);
		[id(5), helpstring("method get_Name")] HRESULT get_Name([out] BSTR *pbstrName);
		[id(6), helpstring("method get_VersionString")] HRESULT get_VersionString([out] BSTR *pbstrVersionString);
		[id(7), helpstring("method put_DialogAutoCloseTime")] HRESULT put_DialogAutoCloseTime([in] ULONG uSeconds);
		[id(8), helpstring("method put_INIPathname")] HRESULT put_INIPathname([in] BSTR bstrPathname);
		[id(9), helpstring("method put_Name")] HRESULT put_Name([in] BSTR bstrName);

		[id(10), helpstring("method put_WindowsRegisteredMessageStrings")]
		HRESULT put_WindowsRegisteredMessageStrings(
			[in] ULONG ulRECEIVE,
			[in] ULONG ulRECEIVE_OOB,
			[in] ULONG ulSTART,
			[in] ULONG ulSTOP,
			[in] ULONG ulRESET);

		[id(11), helpstring("method put_ThresholdValue")] HRESULT put_ThresholdValue([in] ULONG uThresholdValue);

		[id(12), helpstring("method RegisterISO")] 
		HRESULT RegisterISO(
			[in] ULONG uReceiverHandle,
			[in] ULONG uNode,
			[in] ISO_FUNCTIONAL_CATEGORY eCategory,
			[in] VARIANT_BOOL vbOOB, 
			[out] VARIANT_BOOL *pvbResult);

		[id(13), helpstring("method ResetCSO")]HRESULT ResetCSO();
		[id(14), helpstring("method SendHeartbeat")] HRESULT SendHeartbeat();
		[id(15), helpstring("method SendToWatch")] HRESULT SendToWatch([in] BSTR bstrDisplayString, [in] ULONG uNode);
		[id(16), helpstring("method SetUpPort")] HRESULT SetUpPort([in] BSTR bstrPortName, [out] VARIANT_BOOL *pvbResult);
		[id(17), helpstring("method ShutdownCSO")] HRESULT ShutdownCSO();
		[id(18), helpstring("method StartCSO")] HRESULT StartCSO();

		[id(19), helpstring("method Transmit")] 
		HRESULT Transmit(
			[in] ULONG uLength,
			[in] BLOB blobData, 
			[in] ULONG uNode, 
			[in] VARIANT_BOOL vbQuiet, 
			[out] ULONG *puBytesWritten);

		[id(20), helpstring("method UnRegisterISO")] HRESULT UnRegisterISO([in] ULONG uNode, [in] ISO_FUNCTIONAL_CATEGORY eCategory);

	};