//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MicMgr.rc
//
#define ID_HIDDEN_EXTEND                3
#define IDM_ABOUTBOX                    0x0010
#define IDM_CONFIG_ALT                  0x0020
#define IDM_ACCESS_ALT                  0x0030
#define IDM_EXIT_ALT                    0x0040
#define IDM_COPY_ALT                    0x0050
#define IDM_DELETE_ALT                  0x0060
#define IDM_CEREAL_BOWL                 0x0061
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MIC_DIALOG                  102
#define IDD_VALIDATE_DIALOG             103
#define IDD_MESSAGE_DIALOG              104
#define IDD_ACCESS_DIALOG               105
#define IDD_USERINFO_DIALOG             106
#define IDD_CONFIGURE_DIALOG            107
#define IDD_NEWINST_DIALOG              108
#define IDD_DELETEINS_DIALOG            109
#define IDD_NEWCOMM_DIALOG              110
#define IDM_ARCH_ALT                    0x006f
#define IDM_DATA_ALT                    0x0070
#define IDM_REORG_ALT                   0x0071
#define IDM_DT0PAUSE                    0x0072
#define IDD_DELETECOMM_DIALOG           114
#define IDD_REORG_DLG                   115
#define IDD_DIALOG_RENAME               116
#define IDD_TIMED_INTEGER_DIALOG        117
#define IDD_COPYFILES1_DIALOG           118
#define IDD_COPYFILES4_DIALOG           119
#define IDR_MAINFRAME                   120
#define IDI_ICON1                       121
#define IDI_ICON_RED                    122
#define IDI_ICON_GREENT                 124
#define IDI_ICON_YELLOWR                125
#define IDI_ICON_GRAY                   126
#define IDI_ICON_GRAYT                  127
#define IDD_DIALOG1                     128
#define IDB_BMP_GREEN                   130
#define IDB_BMP_ALL                     131
#define IDB_BMP_GREENT                  132
#define IDB_BITMAP1                     133
#define IDB_BITMAP2                     134
#define IDB_BITMAP3                     135
#define IDB_BITMAP4                     136
#define IDB_BITMAP5                     137
#define IDB_BITMAP6                     138
#define IDB_BITMAP7                     139
#define IDB_BITMAP8                     140
#define IDI_ICON2                       180
#define IDI_ICON3                       181
#define IDI_ICON4                       182
#define IDI_ICON9                       190
#define IDI_ICON10                      191
#define IDI_ICON11                      194
#define IDI_ICON12                      195
#define IDC_STATIC_VERSION              200
#define IDC_COPYDATA_BUTTON             201
#define IDC_STARTDATA_BUTTON            203
#define IDC_ALL_STATIC                  204
#define IDC_USERNAME_EDIT               205
#define IDC_PASSWORD_EDIT               206
#define IDC_MESSAGE_STATIC              207
#define IDC_USER_LIST                   208
#define IDC_NEW_BUTTON                  209
#define IDC_EDIT_BUTTON                 210
#define IDC_DELETE_BUTTON               211
#define IDC_PASSWORD1_EDIT              212
#define IDC_PASSWORD2_EDIT              213
#define IDC_CHECK_USESHORT              214
#define IDC_EDIT_LONGNAME               215
#define IDC_APPLY_BUTTON                216
#define IDC_FACILITYNAME_EDIT           217
#define IDC_HIDEWINDOWS_CHECK           218
#define IDC_COLUMN_SPIN                 219
#define IDC_DAYSTOKEEPDATA_SPIN         220
#define IDC_DAYSBEFOREDELFILES_SPIN     221
#define IDC_MAXREPETITION_SPIN          222
#define IDC_ADDINST_BUTTON              223
#define IDC_DELINST_BUTTON              224
#define IDC_ADDCOMM_BUTTON              225
#define IDC_DELCOMM_BUTTON              226
#define IDC_DIALOG_SPIN                 227
#define IDC_BROWSEDEST_BUTTON           228
#define IDC_DESTINATIONNAME_EDIT        229
#define IDC_HEIGHT_SPIN                 230
#define IDC_WIDTH_SPIN                  231
#define IDC_FLAG_SPIN                   232
#define IDC_LOGARCHIVEACT_CHECK         233
#define IDC_NOPAUSERESTART_CHECK        234
#define IDC_MAXPERCENTDISKUSE_STATIC    235
#define IDC_INSTCOLUMNS_STATIC          236
#define IDC_DAYSTOKEEPDATA_STATIC       237
#define IDC_DAYSBEFOREDELFILES_STATIC   238
#define IDC_MAXREPETITION_STATIC        239
#define IDC_WIDTH                       240
#define IDC_HEIGHT                      241
#define IDC_FLAG                        242
#define IDC_DIALOG_STATIC               243
#define IDC_STATIC_EXAMPLE              244
#define IDC_STATIC_BBMTOTAL             245
#define IDC_INSTNAME_EDIT               246
#define IDC_INSTTYPE_LIST               247
#define IDC_CREATE_NEWINST_BUTTON       248
#define IDC_DELETE_LIST                 250
#define IDC_COMMNAME_EDIT               251
#define IDC_COMMTYPE_LIST               252
#define IDC_CREATE_NEWCOMM_BUTTON       253
#define IDI_ICON13                      254
#define IDC_EDIT_NEWNAME                255
#define IDC_STATIC_CURRENTNAME          256
#define IDC_STATIC_ORIGINALNAME         257
#define IDC_EDIT_NEWNODE                258
#define IDC_STATIC_EXISTINGNODE         259
#define IDC_STATIC_ORIGINALNODE         260
#define IDC_LIST1                       261
#define IDC_MOVE_UP                     262
#define IDC_MOVE_DOWN                   263
#define IDOK2                           264
#define IDC_RENAME_SELECTED             265
#define IDC_RENAME_REVERT               266
#define IDC_TREE_VIEW                   273
#define IDC_CHECK_HIDEWATCH             274
#define IDC_EDIT_TIMED_INTEGER_1        276
#define IDD_DIALOG2                     276
#define IDC_EDIT_TIMED_INTEGER_2        277
#define IDC_CHECK_LIMITED               278
#define IDD_DIALOG3                     278
#define IDC_STATIC_TIMED_INTEGER_MSG_1  279
#define IDC_STATIC_TIMED_INTEGER_MSG_2  280
#define IDC_STATIC_TIMED_INTEGER_MSG_3  281
#define IDC_CHECK_APPEND                282
#define IDC_SPIN_TIMED_INTEGER          283
#define IDC_BUTTON_BROWSE               284
#define IDD_COMPORTLIST                 285
#define IDC_STATIC_DEBUG                1002
#define IDC_DATETIMEPICKER1             1003
#define IDC_CHECK1                      1004
#define IDC_EDIT1                       1006
#define IDC_BUTTON_REGISTER             1007
#define IDC_STATIC_MESSAGE              1008
#define IDC_PORTLIST                    1009
#define IDC_BEGINCOPY_BUTTON            1230
#define IDC_TOCLOSE_BUTTON              1231
#define IDC_ICON_1                      1232
#define IDC_ICON_2                      1233
#define IDC_ICON_3                      1234
#define IDC_ICON_4                      1235
#define IDC_ICON_5                      1236
#define IDC_ICON_6                      1237
#define IDC_ICON_7                      1238
#define IDC_ICON_8                      1239
#define IDC_DUMP_PROGRESS               1240
#define IDC_INSPECTORID_EDIT            1241
#define IDC_INSPECTION_EDIT             1242
#define IDC_INSPECTORNAME_EDIT          1243
#define IDC_DRIVEDEF_RADIO              1244
#define IDC_TILLCLOSE_BUTTON            1245
#define IDC_DRIVE1_RADIO                1246
#define IDC_DRIVE3_RADIO                1248
#define IDC_DRIVE5_RADIO                1249
#define IDC_DRIVE7_RADIO                1250
#define IDC_DRIVE2_RADIO                1251
#define IDC_DRIVE4_RADIO                1252
#define IDC_DRIVE6_RADIO                1253
#define IDC_DRIVE8_RADIO                1254
#define IDC_FILE_LIST                   1260
#define IDC_UNDO_BUTTON                 1261
#define IDC_DESTINATION_STATIC          1262
#define IDC_NEXT_STATIC                 1263
#define IDC_DUMP_MESSAGE                1264
#define IDC_IAEA_STATIC                 1265
#define IDC_PREVIOUS_STATIC             1266
#define IDC_FACILITYNAME_STATIC         1267
#define IDC_TODAYSDATE_STATIC           1268
#define IDC_TOTALMEDIA_STATIC           1269
#define IDC_TOTAL_STATIC                1270
#define IDC_SELECTED_STATIC             1271
#define IDC_CAUTION_STATIC              1272
#define IDC_BUTTON_CF_BROWSE            1274
#define IDC_BUTTON_REVIEW               6000
#define IDC_INSTRUMENT_BUTTON           7000
#define IDC_COPY_DONE                   20021
#define IDC_FORCE_PAUSE                 20022
#define IDC_CREATE_COMM                 20120
#define IDC_CREATE_INST                 20125
#define IDC_DELETE_COMM                 20130
#define IDC_DELETE_INST                 20131
#define IDC_COPY_DATA                   20200
#define IDC_TIME_CHECK                  22222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        286
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
